# Form implementation generated from reading ui file '.\NewAppDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
from abstractUiClasses import confirmDialog


class NewAppDialog(object):
    def __init__(self, appList):
        self.appList = appList

    def setupUi(self, Dialog):
        self.parent = Dialog

        Dialog.setObjectName("Dialog")
        Dialog.resize(420, 134)

        self.formLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 30, 381, 61))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")

        self.label_appName = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_appName.setObjectName("label_appName")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_appName
        )

        self.lineEdit_appName = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEdit_appName.setObjectName("lineEdit_appName")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_appName
        )

        self.label_appId = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_appId.setObjectName("label_appId")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_appId
        )

        self.lineEdit_appId = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEdit_appId.setObjectName("lineEdit_appId")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_appId
        )

        self.pushButton_ok = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_ok.setGeometry(QtCore.QRect(240, 100, 75, 24))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.pushButton_ok.clicked.connect(self.onClick_pushButton_ok)

        self.pushButton_cancel = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_cancel.setGeometry(QtCore.QRect(320, 100, 75, 24))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.pushButton_cancel.clicked.connect(self.onClick_pushButton_cancel)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))

        self.label_appName.setText(_translate("Dialog", "App Name :"))
        self.label_appId.setText(_translate("Dialog", "App Id :"))

        self.pushButton_ok.setText(_translate("Dialog", "Ok"))
        self.pushButton_cancel.setText(_translate("Dialog", "Cancel"))

    def onClick_pushButton_ok(self):
        if self.lineEdit_appName.text() == "" or self.lineEdit_appId.text() == "":
            popup = QtWidgets.QDialog()
            layout = QtWidgets.QVBoxLayout()
            message = QtWidgets.QLabel("Please make sure both fields are filled.")
            layout.addWidget(message)
            popup.setLayout(layout)
            popup.exec()
        else:
            self.appList.append(
                {
                    "appName": self.lineEdit_appName.text(),
                    "appId": self.lineEdit_appId.text(),
                }
            )
            self.parent.close()

    def onClick_pushButton_cancel(self):
        self.parent.close()


class ChangeAppDialog(object):
    def __init__(self, appList, itemIndex):
        self.appList = appList
        self.itemIndex = itemIndex

    def setupUi(self, Dialog):
        self.parent = Dialog

        Dialog.setObjectName("Dialog")
        Dialog.resize(420, 134)

        self.formLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 30, 381, 61))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")

        self.label_appName = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_appName.setObjectName("label_appName")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_appName
        )

        self.lineEdit_appName = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEdit_appName.setObjectName("lineEdit_appName")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_appName
        )
        self.lineEdit_appName.setText(self.appList[self.itemIndex]["appName"])

        self.label_appId = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_appId.setObjectName("label_appId")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_appId
        )

        self.lineEdit_appId = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEdit_appId.setObjectName("lineEdit_appId")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_appId
        )
        self.lineEdit_appId.setText(self.appList[self.itemIndex]["appId"])

        self.pushButton_deleteApp = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_deleteApp.setGeometry(QtCore.QRect(20, 100, 75, 24))
        self.pushButton_deleteApp.setObjectName("pushButton")
        self.pushButton_deleteApp.clicked.connect(self.onClick_pushButton_deleteApp)

        self.pushButton_save = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_save.setGeometry(QtCore.QRect(240, 100, 75, 24))
        self.pushButton_save.setObjectName("pushButton_ok")
        self.pushButton_save.clicked.connect(self.onClick_pushButton_save)

        self.pushButton_cancel = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_cancel.setGeometry(QtCore.QRect(320, 100, 75, 24))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.pushButton_cancel.clicked.connect(self.onClick_pushButton_cancel)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))

        self.label_appName.setText(_translate("Dialog", "App Name :"))
        self.label_appId.setText(_translate("Dialog", "App Id :"))

        self.pushButton_deleteApp.setText(_translate("Dialog", "Delete App"))
        self.pushButton_save.setText(_translate("Dialog", "Save"))
        self.pushButton_cancel.setText(_translate("Dialog", "Cancel"))

    def onClick_pushButton_deleteApp(self):
        dialog_confirmDelete = QtWidgets.QDialog()
        obj_confirmDelete = confirmDelete(
            "Are you sure you want to delete this app?",
            self.appList,
            self.itemIndex,
            self.parent,
        )
        obj_confirmDelete.setupUi(dialog_confirmDelete)
        dialog_confirmDelete.exec()

    def onClick_pushButton_save(self):
        if (
            self.lineEdit_appName.text() != self.appList[self.itemIndex]["appName"]
            or self.lineEdit_appId.text() != self.appList[self.itemIndex]["appId"]
        ):
            self.appList[self.itemIndex]["appName"] = self.lineEdit_appName.text()
            self.appList[self.itemIndex]["appId"] = self.lineEdit_appId.text()
        self.parent.close()

    def onClick_pushButton_cancel(self):
        if (
            self.lineEdit_appName.text() != self.appList[self.itemIndex]["appName"]
            or self.lineEdit_appId.text() != self.appList[self.itemIndex]["appId"]
        ):
            dialog_confirmDiscardChange = QtWidgets.QDialog()
            obj_confirmDiscardChange = confirmDiscardChange(
                "App has unsaved changes. \nDo you want to discard changes?",
                self.parent,
            )
            obj_confirmDiscardChange.setupUi(dialog_confirmDiscardChange)
            dialog_confirmDiscardChange.exec()
        else:
            self.parent.close()


class confirmDelete(confirmDialog):
    def __init__(self, text, appList, itemIndex, editDeleteDialog):
        super().__init__(text)
        self.appList = appList
        self.itemIndex = itemIndex
        self.parentDialog = editDeleteDialog

    def onClick_pushButton_no(self):
        return super().onClick_pushButton_no()

    def onClick_pushButton_yes(self):
        self.appList.pop(self.itemIndex)
        self.parent.close()
        self.parentDialog.close()


class confirmDiscardChange(confirmDialog):
    def __init__(self, text, editDeleteDialog):
        super().__init__(text)
        self.parentDialog = editDeleteDialog

    def onClick_pushButton_no(self):
        return super().onClick_pushButton_no()

    def onClick_pushButton_yes(self):
        self.parent.close()
        self.parentDialog.close()
